version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command: ["postgres"]

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "yuri.escada@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  sql:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: zabbix
       MYSQL_DB: zabbix
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: zabbix
     volumes:
      - ./zabbix-mysql:/home/grey/mysql
     restart: always

  zabbix:
     image: zabbix/zabbix-server-mysql:latest
     environment:
          DB_SERVER_HOST: sql
          MYSQL_DB: zabbix
          MYSQL_USER: root
          MYSQL_PASSWORD: zabbix
          ZBX_VALUECACHESIZE: 64M
          ZBX_CACHESIZE: 128M
          ZBX_TRENDCACHESIZE: 128M
          ZBX_ALLOWUNSUPPORTEDDBVERSIONS: "1" 
     volumes:
      - ./zabbix-serv:/home/grey/zabbix-server
     restart: always
     depends_on:
       - sql
    
  zabbix-web:
     image:  zabbix/zabbix-web-apache-mysql
     environment:
        DB_SERVER_HOST: sql
        MYSQL_USER: root
        MYSQL_PASSWORD: zabbix
        MYSQL_DB: zabbix
        ZBX_SERVER_HOST: zabbix
        ZBX_SERVER_PORT: 10051
        PHP_TZ: America/Sao_Paulo
     ports:
      - "8999:8080"
     restart: always
     depends_on:
       - zabbix-agenr

  zabbix-agenr:
     image:  zabbix/zabbix-agent
     environment:
        DB_SERVER_HOST: sql
        MYSQL_USER: root
        MYSQL_PASSWORD: zabbix
        MYSQL_DB: zabbix
        ZBX_SERVER_PORT: 10051
        ZBX_SERVER_HOST: zabbix
     restart: always
     depends_on:
       - zabbix

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana_password
    volumes:
      - ./grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
