name: CI

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  dockerhub:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'yurisbk'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: 'yurisbk/techchallenge_imagem:latest'
          push: true

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./scripts:/docker-entrypoint-initdb.d

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.204'

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U root -d root; then
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Run database initialization script
        run: psql -h localhost -U root -d root -f scripts/docker-database-initial.sql
        env:
          PGPASSWORD: root

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --filter Category=Unity --verbosity normal

      - name: Run integration tests
        run: dotnet test --no-build --filter Category=Integration --verbosity normal
        env:
          PGPASSWORD: root


          