name: CI

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  dockerhub:
    name: Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'yurisbk'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: 'yurisbk/techchallenge_imagem:latest'
          push: true

  build_and_test:
    name: Executando segundo job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        run: Docker-Compose up -d --build

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.204'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --filter "Category=Unity" --verbosity detailed --logger "trx;LogFileName=unit_tests.trx"

      - name: Run integration tests
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Username=root;Password=root;Database=root"
        run: dotnet test --no-build --filter "Category=Integration" --verbosity detailed --logger "trx;LogFileName=integration_tests.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/unit_tests.trx
            **/integration_tests.trx

      - name: Teardown Docker Compose
        if: always()
        run: docker-compose down
