name: CI

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  dockerhub:
    name: Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'yurisbk'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t yurisbk/techchallenge_imagem:latest .
          docker push yurisbk/techchallenge_imagem:latest

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Checkout do código
        uses: actions/checkout@v2  

      - name: Run unit tests
        run: dotnet test --filter "Category=Unity"

      - name: Run integration tests
        run: dotnet test --filter "Category=Integration"

      - name: Publish API
        run: dotnet publish ./src/TechChallenge_ControleContatos -c Release -o ./publish

